services:
  veloma-app:
    ports:
      - "19082:3000"
  veloma-api:
    ports:
      - "19080:8000"
  veloma-postgres:
    ports:
      - "19032:5432"
  veloma-redis:
    ports:
      - "19079:6379"
  veloma-minio:
    ports:
      - "19090:9000"
      - "19091:9001"
