# Generated by Django 5.2.6 on 2025-09-19 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EmailProvider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('code', models.SlugField(unique=True)),
                ('provider', models.CharField(choices=[('smtp', 'Generic SMTP'), ('console', 'Django Console'), ('filebased', 'Django File-Based')], default='smtp', max_length=20)),
                ('is_default', models.BooleanField(default=True)),
                ('host', models.CharField(blank=True, max_length=255)),
                ('port', models.PositiveIntegerField(default=587)),
                ('username', models.CharField(blank=True, max_length=255)),
                ('password', models.CharField(blank=True, max_length=255)),
                ('use_tls', models.BooleanField(default=True)),
                ('use_ssl', models.BooleanField(default=False)),
                ('timeout', models.PositiveIntegerField(default=30)),
                ('file_path', models.CharField(blank=True, max_length=255)),
                ('from_email_default', models.EmailField(blank=True, max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='ServiceToggle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=50, unique=True)),
                ('enabled', models.BooleanField(default=True)),
                ('notes', models.TextField(blank=True)),
            ],
        ),
    ]
