# Generated by Django 5.2.16 on 2026-07-23 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('veloma_client_portal', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientfolder',
            name='visibility',
            field=models.CharField(choices=[('client_and_staff', 'Client and staff'), ('staff_only', 'Staff only')], db_index=True, default='client_and_staff', max_length=20),
        ),
    ]
