# Generated by Django 5.2.16 on 2026-07-23 20:23

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('veloma_client_portal', '0002_clientfolder_visibility'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TermsAcceptance',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('email_snapshot', models.EmailField(blank=True, max_length=254)),
                ('client_name_snapshot', models.CharField(blank=True, max_length=255)),
                ('context', models.CharField(choices=[('invitation', 'Invitation acceptance'), ('first_access', 'First access')], default='invitation', max_length=32)),
                ('terms_version', models.CharField(max_length=32)),
                ('privacy_version', models.CharField(max_length=32)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('country_code', models.CharField(blank=True, max_length=8)),
                ('region', models.CharField(blank=True, max_length=128)),
                ('device', models.CharField(blank=True, max_length=255)),
                ('user_agent', models.TextField(blank=True)),
                ('pdf_storage_key', models.CharField(blank=True, max_length=512)),
                ('archived_path', models.CharField(blank=True, max_length=512)),
                ('archived_at', models.DateTimeField(blank=True, null=True)),
                ('accepted_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='terms_acceptances', to='veloma_client_portal.client')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='veloma_terms_acceptances', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Terms acceptance',
                'verbose_name_plural': 'Terms acceptances',
                'db_table': 'client_portal_terms_acceptance',
                'ordering': ('-accepted_at',),
            },
        ),
    ]
