# Generated by Django 5.2.16 on 2026-07-23 21:55

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('veloma_client_portal', '0003_termsacceptance'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProtocolSubject',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=120, unique=True)),
                ('description', models.TextField(blank=True, help_text='Shown to the client when choosing the subject.')),
                ('category', models.CharField(blank=True, max_length=32)),
                ('sla_hours', models.PositiveIntegerField(default=48, help_text='Hours the office has to respond.')),
                ('active', models.BooleanField(db_index=True, default=True)),
                ('order', models.PositiveSmallIntegerField(default=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Protocol subject',
                'verbose_name_plural': 'Protocol subjects',
                'db_table': 'client_portal_protocol_subject',
                'ordering': ('order', 'name'),
            },
        ),
        migrations.AddField(
            model_name='protocol',
            name='response_due_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='protocol',
            name='sla_hours',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='protocol',
            name='subject',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='protocols', to='veloma_client_portal.protocolsubject'),
        ),
    ]
