# Generated by Django 5.2.16 on 2026-07-23 22:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('veloma_client_portal', '0005_document_deleted_at_document_deleted_by_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeletedDocument',
            fields=[
            ],
            options={
                'verbose_name': 'Documento eliminado',
                'verbose_name_plural': 'Documentos eliminados',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('veloma_client_portal.document',),
        ),
    ]
