# Generated by Django 5.2.16 on 2026-07-23 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('veloma_client_portal', '0006_deleteddocument'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='note',
            field=models.TextField(blank=True),
        ),
    ]
