# Generated by Django 5.2.16 on 2026-07-23 23:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('veloma_client_portal', '0007_document_note'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DeletedDocument',
        ),
    ]
