# Generated by Django 5.2.16 on 2026-07-24 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('veloma_client_portal', '0008_delete_deleteddocument'),
    ]

    operations = [
        migrations.AddField(
            model_name='termsacceptance',
            name='verification_hash',
            field=models.CharField(blank=True, db_index=True, max_length=64),
        ),
    ]
