# Generated by Django 5.2.16 on 2026-07-23 15:42

import django.contrib.auth.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('veloma_authentication', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ArchivedAccount',
            fields=[
            ],
            options={
                'verbose_name': 'Archived account',
                'verbose_name_plural': 'Archived accounts',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('auth.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='AccountLifecycle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deactivated_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('deactivation_reason', models.CharField(blank=True, max_length=255)),
                ('archived_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('archive_reason', models.CharField(blank=True, max_length=255)),
                ('last_reactivated_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('archived_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='veloma_archived_accounts', to=settings.AUTH_USER_MODEL)),
                ('deactivated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='veloma_deactivated_accounts', to=settings.AUTH_USER_MODEL)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='veloma_lifecycle', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Account lifecycle',
                'verbose_name_plural': 'Account lifecycle',
                'db_table': 'authentication_account_lifecycle',
                'ordering': ('-updated_at',),
            },
        ),
    ]
