# Generated by Django 5.2.16 on 2026-07-23 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('veloma_authentication', '0002_archivedaccount_accountlifecycle'),
    ]

    operations = [
        migrations.AddField(
            model_name='accountlifecycle',
            name='credentials_updated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='accountlifecycle',
            name='must_change_credentials',
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
