# Generated by Django 5.2.16 on 2026-07-23 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('veloma_authentication', '0003_accountlifecycle_credentials_updated_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='accountlifecycle',
            name='two_factor_email_enabled',
            field=models.BooleanField(default=False),
        ),
    ]
