# Generated by Django 5.2.16 on 2026-07-23 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('veloma_authentication', '0004_accountlifecycle_two_factor_email_enabled'),
    ]

    operations = [
        migrations.AddField(
            model_name='accountlifecycle',
            name='notifications_seen_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='accountlifecycle',
            name='sound_enabled',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='accountlifecycle',
            name='theme',
            field=models.CharField(choices=[('light', 'Light'), ('dark', 'Dark')], default='light', max_length=8),
        ),
    ]
