# Generated by Django 5.2.16 on 2026-07-24 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('veloma_authentication', '0005_accountlifecycle_notifications_seen_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='accountlifecycle',
            name='notifications_cleared_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
