import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True
    dependencies = []
    operations = [
        migrations.CreateModel(
            name='AuthenticationSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registration_enabled', models.BooleanField(default=True)),
                ('email_verification_required', models.BooleanField(default=True)),
                ('login_otp_enabled', models.BooleanField(default=False)),
                ('default_frontend_group', models.CharField(default='USER', max_length=80)),
                ('deny_django_admin_api_login', models.BooleanField(default=True)),
                ('otp_length', models.PositiveSmallIntegerField(default=6)),
                ('otp_expiration_minutes', models.PositiveSmallIntegerField(default=5)),
                ('otp_max_attempts', models.PositiveSmallIntegerField(default=5)),
                ('otp_resend_cooldown_seconds', models.PositiveIntegerField(default=60)),
                ('otp_max_resends', models.PositiveSmallIntegerField(default=3)),
                ('password_reset_expiration_minutes', models.PositiveSmallIntegerField(default=10)),
                ('revoke_sessions_after_password_reset', models.BooleanField(default=True)),
                ('revoke_sessions_after_password_change', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={'verbose_name': 'Authentication settings', 'verbose_name_plural': 'Authentication settings'},
        ),
        migrations.CreateModel(
            name='SecuritySettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('login_max_attempts', models.PositiveSmallIntegerField(default=5)),
                ('login_window_minutes', models.PositiveSmallIntegerField(default=15)),
                ('automatic_block_minutes', models.PositiveIntegerField(default=30)),
                ('block_user_on_failed_login', models.BooleanField(default=True)),
                ('block_ip_on_failed_login', models.BooleanField(default=True)),
                ('max_active_sessions', models.PositiveSmallIntegerField(default=3)),
                ('session_activity_touch_seconds', models.PositiveIntegerField(default=60)),
                ('api_rate_limit_enabled', models.BooleanField(default=True)),
                ('api_rate_limit_requests', models.PositiveIntegerField(default=120)),
                ('api_rate_limit_window_seconds', models.PositiveIntegerField(default=60)),
                ('auth_rate_limit_requests', models.PositiveIntegerField(default=30)),
                ('auth_rate_limit_window_seconds', models.PositiveIntegerField(default=60)),
                ('ip_intelligence_enabled', models.BooleanField(default=False)),
                ('ip_intelligence_url', models.CharField(blank=True, help_text='Endpoint template. Use {ip} where the client IP must be inserted.', max_length=500)),
                ('encrypted_ip_intelligence_token', models.TextField(blank=True, editable=False)),
                ('ip_intelligence_timeout_seconds', models.PositiveSmallIntegerField(default=3)),
                ('block_unknown_countries', models.BooleanField(default=False)),
                ('allowed_country_codes', models.CharField(blank=True, help_text='Comma-separated ISO country codes.', max_length=512)),
                ('notify_new_device', models.BooleanField(default=True)),
                ('notify_new_ip', models.BooleanField(default=False)),
                ('notify_new_country', models.BooleanField(default=True)),
                ('authentication_record_retention_days', models.PositiveIntegerField(default=30)),
                ('audit_log_retention_days', models.PositiveIntegerField(default=180)),
                ('email_log_retention_days', models.PositiveIntegerField(default=90)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={'verbose_name': 'Security settings', 'verbose_name_plural': 'Security settings'},
        ),
        migrations.CreateModel(
            name='EmailSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('default_delivery_mode', models.CharField(choices=[('sync', 'Sync'), ('async', 'Async'), ('auto', 'Auto')], default='auto', max_length=10)),
                ('auto_sync_fallback', models.BooleanField(default=True)),
                ('max_retries', models.PositiveSmallIntegerField(default=3)),
                ('retry_backoff_seconds', models.PositiveIntegerField(default=30)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={'verbose_name': 'Email settings', 'verbose_name_plural': 'Email settings'},
        ),
        migrations.CreateModel(
            name='EmailVendor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, unique=True)),
                ('vendor_type', models.CharField(choices=[('smtp', 'SMTP'), ('console', 'Development console')], default='smtp', max_length=20)),
                ('host', models.CharField(blank=True, max_length=255)),
                ('port', models.PositiveIntegerField(default=587)),
                ('username', models.CharField(blank=True, max_length=255)),
                ('encrypted_password', models.TextField(blank=True, editable=False)),
                ('use_tls', models.BooleanField(default=True)),
                ('use_ssl', models.BooleanField(default=False)),
                ('from_email', models.EmailField(blank=True, max_length=254)),
                ('from_name', models.CharField(blank=True, max_length=120)),
                ('reply_to', models.EmailField(blank=True, max_length=254)),
                ('timeout_seconds', models.PositiveSmallIntegerField(default=30)),
                ('priority', models.PositiveSmallIntegerField(default=100)),
                ('active', models.BooleanField(db_index=True, default=True)),
                ('is_default', models.BooleanField(default=False)),
                ('is_fallback', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={'verbose_name': 'Email vendor', 'verbose_name_plural': 'Email vendors', 'ordering': ('priority', 'name')},
        ),
        migrations.CreateModel(
            name='EmailTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('purpose', models.SlugField(max_length=100, unique=True)),
                ('subject', models.CharField(max_length=255)),
                ('html_template', models.CharField(max_length=255)),
                ('text_template', models.CharField(max_length=255)),
                ('delivery_mode', models.CharField(choices=[('sync', 'Sync'), ('async', 'Async'), ('auto', 'Auto')], default='auto', max_length=10)),
                ('active', models.BooleanField(db_index=True, default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('vendor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='templates', to='veloma_configuration.emailvendor')),
            ],
            options={'verbose_name': 'Email template', 'verbose_name_plural': 'Email templates', 'ordering': ('purpose',)},
        ),
        migrations.CreateModel(
            name='EmailDeliveryLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('purpose', models.CharField(blank=True, db_index=True, max_length=100)),
                ('recipients', models.JSONField(default=list)),
                ('subject', models.CharField(max_length=255)),
                ('delivery_mode', models.CharField(max_length=10)),
                ('status', models.CharField(choices=[('queued', 'Queued'), ('sent', 'Sent'), ('failed', 'Failed')], db_index=True, max_length=16)),
                ('task_id', models.CharField(blank=True, max_length=255)),
                ('attempts', models.PositiveSmallIntegerField(default=0)),
                ('error', models.TextField(blank=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('vendor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='veloma_configuration.emailvendor')),
            ],
            options={'verbose_name': 'Email delivery log', 'verbose_name_plural': 'Email delivery logs', 'ordering': ('-created_at',)},
        ),
        migrations.AddConstraint(
            model_name='emailvendor',
            constraint=models.UniqueConstraint(condition=models.Q(('is_default', True)), fields=('is_default',), name='single_default_email_vendor'),
        ),
    ]
