# Generated by Django 5.2.16 on 2026-07-23 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('veloma_configuration', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('allowed_extensions', models.CharField(default='pdf,xml,csv,xls,xlsx,doc,docx,jpg,jpeg,png,zip', help_text='Comma-separated extensions, without dots.', max_length=512)),
                ('max_file_size_mb', models.PositiveIntegerField(default=25)),
                ('max_files_per_protocol', models.PositiveIntegerField(default=200)),
                ('allow_zip', models.BooleanField(default=True)),
                ('require_antivirus', models.BooleanField(default=False, help_text='When enabled, a scanner failure keeps the file in quarantine.')),
                ('antivirus_host', models.CharField(blank=True, default='veloma-clamav', max_length=180)),
                ('antivirus_port', models.PositiveIntegerField(default=3310)),
                ('antivirus_timeout_seconds', models.PositiveSmallIntegerField(default=30)),
                ('signed_url_seconds', models.PositiveIntegerField(default=300)),
                ('quarantine_retention_days', models.PositiveIntegerField(default=30)),
                ('invitation_expiration_days', models.PositiveSmallIntegerField(default=7)),
                ('invitation_reminder_days', models.PositiveSmallIntegerField(default=3)),
                ('invitation_max_resends', models.PositiveSmallIntegerField(default=5)),
                ('overdue_alert_enabled', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Document settings',
                'verbose_name_plural': 'Document settings',
            },
        ),
    ]
