# Generated by Django 5.2.16 on 2026-07-23 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('veloma_configuration', '0002_documentsettings'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentsettings',
            name='client_allowed_extensions',
            field=models.CharField(default='zip', help_text='Extensions clients may upload. Defaults to ZIP only, so each delivery arrives as one package.', max_length=512),
        ),
        migrations.AlterField(
            model_name='documentsettings',
            name='allowed_extensions',
            field=models.CharField(default='pdf,xml,csv,xls,xlsx,doc,docx,jpg,jpeg,png,zip', help_text='Comma-separated extensions, without dots. Applies to staff uploads.', max_length=512),
        ),
    ]
