# Generated by Django 5.2.16 on 2026-07-23 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('veloma_configuration', '0003_documentsettings_client_allowed_extensions_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DropboxSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enabled', models.BooleanField(default=False)),
                ('app_key', models.CharField(blank=True, max_length=255)),
                ('encrypted_app_secret', models.TextField(blank=True, editable=False)),
                ('encrypted_refresh_token', models.TextField(blank=True, editable=False)),
                ('mirror_uploads', models.BooleanField(default=True)),
                ('uploads_path', models.CharField(default='/veloma_upload', max_length=255)),
                ('mirror_rgpd', models.BooleanField(default=True)),
                ('rgpd_path', models.CharField(default='/rgpd', max_length=255)),
                ('timeout_seconds', models.PositiveSmallIntegerField(default=30)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Dropbox settings',
                'verbose_name_plural': 'Dropbox settings',
            },
        ),
    ]
