# Generated by Django 5.2.16 on 2026-07-23 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('veloma_configuration', '0004_dropboxsettings'),
    ]

    operations = [
        migrations.AddField(
            model_name='dropboxsettings',
            name='is_team',
            field=models.BooleanField(default=False, help_text='Dropbox Business (team) app.'),
        ),
        migrations.AddField(
            model_name='dropboxsettings',
            name='team_member_id',
            field=models.CharField(blank=True, help_text='Optional; defaults to the team admin.', max_length=128),
        ),
        migrations.AlterField(
            model_name='dropboxsettings',
            name='rgpd_path',
            field=models.CharField(default='/Apps/rgpd', max_length=255),
        ),
        migrations.AlterField(
            model_name='dropboxsettings',
            name='uploads_path',
            field=models.CharField(default='/Apps/veloma_upload', max_length=255),
        ),
    ]
