# Generated by Django 5.2.16 on 2026-07-23 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('veloma_configuration', '0005_dropboxsettings_is_team_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dropboxsettings',
            name='path_root_namespace_id',
            field=models.CharField(blank=True, help_text='Team-folder namespace id for shared storage. Blank = member space.', max_length=64),
        ),
    ]
